In [371]:
#Kütüphanelerin içeri alınması
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', -1)

In [372]:
#Datanın içeri alınması
data = pd.read_excel("maindata.xlsx")
data.head()

,kaKartNo,mbAd,mbIkinciAd,mbSoyad,kaEmbossStr,kaKartTuru,kaAsilKartNo,CustomerId,kaIkincilMusteriNo,kaKartStatusu,kaKartAltStatu,kaProductKodu,kaProductKoduAciklama,prSanalFlag,ptTip,ptEndekslemeParaBirimi,ptEndekslemeParaBirimiAdi,kaLimit,kaOncekiLimit,kaLimitDegTarih,kaEkstreKodu,kaEkstreKoduAciklama,kaYeniEkstreKodu,kaYeniEkstreKoduAciklama,KartSubeKodu,KartSubeAdi,kaEkstreStatu,kaEkstreStatuSayi,kaEMailOnlyFlag,kaEMailOnlyFlagDegTarih,EkstreTalimatFaxEv,EkstreTalimatFaxIs,EkstreTalimatFaxResmi,EkstreTalimatEmailEv,EkstreTalimatEmailIs,EkstreTalimatEmailResmi,EkstreTalimatGSMSMS,EkstreTalimatGSMWAP,mEkstreYollamaAdresi,mTakipStatu,mFirmaFlag,mbFirmaAdi,mFirmaEmbossAdi,mbBasvTarih,kaKartGirisTarih,kaKartVadeTarih,kaKartBasTarih,kaKartStatDegTarih,kaKartKapaTarih,kaBKMBildirimTarihi,kaProfilTaksitSayisi,kaOtelemeAySayisi,prBireyselKredi,ProjectId,ProposalId,BranchId,AccountNumber,AccountSuffix,PortfolioClass,PersonType,ProductCode,GoodsOrServiceType,AgreementType,FundingAmount,FundingFEC,DebtFECType,DebtFEC,DebtFER,IsMortgage,MortgageType,PaymentDate,CampaignDetailId,FranchiserId,IncentiveId,OperationLocation,TotalImportCost,ImportRateMargin,FundPool,AdvancePaymentRate,AdvancePaymentAmount,AdvancePaymentFEC,AdvancePaymentType,AdvancePaymentCollectionDate,WhoSatisfyPurchasingVAT,WhoSatisfyFixedAssetInsurance,LeasingPurchasingVATRate,LeasingPurchasingVATAmount,LeasingGoodsOrServiceGroup,LeasingTransferTime,ProjectCollateralStatus,PaymentType,AdvanceClosingDate,CollateralType,CollateralCopmletionDate,IsCommitment,CommitmentDate,HasDebtSpesificExchangeRate,IsEarlyClosure,ProjectDate,NotificationTypeId,Status,ParentProjectId,ClosingType,FundingFER,FundingFecBusinessKey,DebtFecBusinessKey,FundingAmountDebitCorrespond,FXStatus,FundingFXRateTrandate,FundingAmountCorrespond,LeasingTransferDate,OperationForwardDate,OperationAssignDate,OperationProcessDate,LeasingPurchasingSalesVATRate,ProformaInvoiceAmount,IsLifeInsurance,UnitId,CustomTakeOver,AdvanceCollateralClosingDate,CustomerClass,IsProjectFinance,ProjectFinanceId,VIFAccountSuffix,ShippingDate,DocumentedAmount,InsuranceCostAmount,TranBranchId,Score
0,4025900213283250,EMBİYA,SEYFİTTİN,RADİFE,TAMIM MESUT,A,,672994,0,N,,CLESVISALE,TEMASSIZ VISA SALEPLUS,N,1,949,TL,10000,0,20140527,8,AYIN 8. GÜNÜ,,NaN,15,OSMANBEY ŞUBESİ (15),N,0,Y,2011-10-20 00:00:00,N,N,N,Y,N,N,Y,N,E,N,N,,,20070618,20140527,20250131,20140527,19000101,19000101,19000101,0,0,N,687909.0,651245.0,39.0,672994.0,300.0,2.0,0.0,IHTIYACKART,3.0,4.0,3899.0,0.0,0.0,0.0,1.0,NaN,NaN,2015-12-01,0.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,0.0,0.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaT,2.0,NaT,0.0,NaN,0.0,NaN,2015-12-01,NaN,5.0,NaN,NaN,0.0,NaN,NaN,3899.0,1.0,NaN,3899.0,NaT,NaT,NaT,NaT,NaN,NaN,0.0,NaN,0.0,NaT,2.0,NaN,NaN,NaN,NaN,0.0,NaN,39.0,1517
1,4025900256482400,KÖKSAL,,DENİZ,KÖKSAL DENİZ,A,,6137288,0,N,,CLESVISALE,TEMASSIZ VISA SALEPLUS,N,1,949,TL,10000,0,20160126,30,AYIN 30. GÜNÜ,,NaN,35,GAZİANTEP ŞUBESİ (35),N,0,Y,2012-02-27 00:00:00,N,N,N,Y,N,N,Y,N,I,N,N,,,20091203,20160126,20210511,20160127,19000101,19000101,19000101,0,0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1704
2,4025900282283040,ZALİHA,,FİNCAN,DENİZ NURGUL,A,,679462,0,N,,CLESVISALE,TEMASSIZ VISA SALEPLUS,N,1,949,TL,10000,0,20140527,23,AYIN 23. GÜNÜ,,NaN,1,MERKEZ ŞUBE (1),N,0,Y,2011-10-20 00:00:00,N,N,N,Y,N,N,Y,N,I,N,N,,,20070607,20140527,20230904,20140527,19000101,19000101,19000101,0,0,N,387968.0,-766846.0,2.0,679462.0,301.0,2.0,0.0,EGITIMFINANSMANI,3.0,4.0,3500.0,0.0,0.0,0.0,1.0,0.0,NaN,2012-04-05,4783.0,NaN,NaN,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,NaT,1.0,NaN,NaN,NaN,27.0,NaN,0.0,1.0,2012-10-31,2.0,NaT,0.0,NaN,0.0,0.0,2012-03-27,NaN,8.0,NaN,NaN,1.0,NaN,NaN,3500.0,NaN,NaN,3500.0,NaT,2012-04-05 13:41:02.600,2012-04-05 13:40:33.130,2012-12-14 11:21:27.610,NaN,NaN,0.0,225.0,NaN,NaT,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1394
3,4025900288779450,SERDİN,,DENİZ,ÇİLEM KORKUT,A,,140492,0,N,,CLESVISALE,TEMASSIZ VISA SALEPLUS,N,1,949,TL,10000,0,20140617,23,AYIN 23. GÜNÜ,,NaN,114,BAŞAKŞEHİR ŞUBESİ (114),N,0,Y,2011-10-20 00:00:00,N,N,N,Y,N,N,Y,N,I,N,N,,,20021217,20140617,20231022,20140617,19000101,19000101,19000101,0,0,N,596299.0,525609.0,284.0,140492.0,200.0,2.0,0.0,IHTIYACKART,3.0,4.0,4219.0,0.0,0.0,0.0,1.0,NaN,NaN,2015-06-14,0.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,0.0,0.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaT,2.0,NaT,0.0,NaN,0.0,NaN,2015-06-14,NaN,5.0,NaN,NaN,0.0,NaN,NaN,4219.0,1.0,NaN,4219.0,NaT,NaT,NaT,NaT,NaN,NaN,0.0,NaN,0.0,NaT,2.0,NaN,NaN,NaN,NaN,NaN,NaN,284.0,1779
4,4025900288779450,SERDİN,,DENİZ,ÇİLEM KORKUT,A,,140492,0,N,,CLESVISALE,TEMASSIZ VISA SALEPLUS,N,1,949,TL,10000,0,20140617,23,AYIN 23. GÜNÜ,,NaN,114,BAŞAKŞEHİR ŞUBESİ (114),N,0,Y,2011-10-20 00:00:00,N,N,N,Y,N,N,Y,N,I,N,N,,,20021217,20140617,20231022,20140617,19000101,19000101,19000101,0,0,N,612345.0,555195.0,284.0,140492.0,201.0,2.0,0.0,IHTIYACKART,3.0,4.0,6010.0,0.0,0.0,0.0,1.0,NaN,NaN,2015-07-13,0.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,0.0,0.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaT,2.0,NaT,0.0,NaN,0.0,NaN,2015-07-13,NaN,5.0,NaN,NaN,0.0,NaN,NaN,6010.0,1.0,NaN,6010.0,NaT,NaT,NaT,NaT,NaN,NaN,0.0,NaN,0.0,NaT,2.0,NaN,NaN,NaN,NaN,NaN,NaN,284.0,1779

In [373]:
# %99 üstü Boş olan değişkenlerin düşürülmesi
def NanCleaner(columnlist):
    drop = []
    for i in columnlist:
        if data[i].isnull().sum() >= len(data[i]) * 0.99:
            drop.append(i)
        else:
            continue
    print("NaN Olanlar",drop)
    return drop

data.drop(NanCleaner(data.columns), axis=1, inplace=True)

NaN Olanlar ['kaYeniEkstreKoduAciklama', 'FranchiserId', 'IncentiveId', 'AdvancePaymentCollectionDate', 'WhoSatisfyFixedAssetInsurance', 'LeasingPurchasingVATRate', 'LeasingPurchasingVATAmount', 'LeasingTransferTime', 'CommitmentDate', 'ClosingType', 'FundingFecBusinessKey', 'DebtFecBusinessKey', 'FundingFXRateTrandate', 'LeasingTransferDate', 'LeasingPurchasingSalesVATRate', 'ProformaInvoiceAmount', 'IsProjectFinance', 'ProjectFinanceId', 'VIFAccountSuffix', 'ShippingDate', 'InsuranceCostAmount']

In [492]:
#Temiz verinin çekilmesi, bu yukarıdaki işlemler + manuel işlemler ile temizlendi.
newdata = pd.read_excel("NaNClean.xlsx")
CustomerId = newdata.CustomerId
productkodu = newdata.kaProductKodu
newdata.drop("CustomerId",axis=1,inplace=True)
newdata = newdata.drop_duplicates()
newdata.head()

,kaProductKodu,kaOncekiLimit,kaEkstreKodu,KartSubeKodu,kaEkstreStatu,kaEMailOnlyFlag,EkstreTalimatEmailEv,EkstreTalimatGSMSMS,kaProfilTaksitSayisi,PortfolioClass,FundingAmount,Status,FundingFER,FundingAmountDebitCorrespond,FundingAmountCorrespond,IsLifeInsurance,Score
0,CLESVISALE,0,8,15,N,Y,Y,Y,0,2,3899.0,5,0.0,3899.0,3899.0,0,1517
1,CLESVISALE,0,30,35,N,Y,Y,Y,0,0,0.0,0,0.0,0.0,0.0,0,1704
2,CLESVISALE,0,23,1,N,Y,Y,Y,0,2,3500.0,8,1.0,3500.0,3500.0,0,1394
3,CLESVISALE,0,23,114,N,Y,Y,Y,0,2,4219.0,5,0.0,4219.0,4219.0,0,1779
4,CLESVISALE,0,23,114,N,Y,Y,Y,0,2,6010.0,5,0.0,6010.0,6010.0,0,1779

In [493]:
newdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2655 entries, 0 to 2671
Data columns (total 17 columns):
kaProductKodu                   2655 non-null object
kaOncekiLimit                   2655 non-null int64
kaEkstreKodu                    2655 non-null int64
KartSubeKodu                    2655 non-null int64
kaEkstreStatu                   2655 non-null object
kaEMailOnlyFlag                 2655 non-null object
EkstreTalimatEmailEv            2655 non-null object
EkstreTalimatGSMSMS             2655 non-null object
kaProfilTaksitSayisi            2655 non-null int64
PortfolioClass                  2655 non-null int64
FundingAmount                   2655 non-null float64
Status                          2655 non-null int64
FundingFER                      2655 non-null float64
FundingAmountDebitCorrespond    2655 non-null float64
FundingAmountCorrespond         2655 non-null float64
IsLifeInsurance                 2655 non-null int64
Score                           2655 non-null int64
dtypes: float64(4), int64(8), object(5)
memory usage: 373.4+ KB

In [494]:
#Kategorik değişkenlerin handle edilmesi
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
objects = ["kaProductKodu"]
for i in objects:  
    le.fit(newdata[i])
    newdata[i] = le.transform(newdata[i])
    
filename = 'labelencoder.sav'
pickle.dump(le, open(filename, 'wb'))

kategori = ["kaEkstreStatu","kaEMailOnlyFlag","EkstreTalimatEmailEv","EkstreTalimatGSMSMS"]
for i in kategori:
    newdata[i] = newdata[i].astype("category").cat.codes

In [495]:
#Outlier Detection

from sklearn.ensemble import IsolationForest
isolation_forest = IsolationForest(n_estimators=100, contamination = 0.01)
isolation_forest.fit(newdata)

outlier = isolation_forest.predict(newdata)
outliers = np.where(outlier==-1)[0]

newdata.drop(outliers, axis=0, inplace=True)

In [496]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
%matplotlib inline
from sklearn import datasets

km = KMeans(n_clusters=4)

X = newdata[["kaProductKodu","KartSubeKodu","kaEkstreStatu"]]
km.fit(X)
km.predict(X)
labels = km.labels_

In [497]:
newdata["Grup"] = labels

In [498]:
newdata.Grup.value_counts()

2    1058
0    632
1    540
3    398
Name: Grup, dtype: int64

In [499]:
newdata["CustomerId"] = CustomerId

In [500]:
filename = 'kmeans.sav'
pickle.dump(km, open(filename, 'wb'))

In [502]:
newdata["kaProductKodu"] = productkodu
newdata[newdata.Grup == 0]


#Limitler Bazında
#Grup 0 Öğrenciler Çünkü Kredi Kartı Limitleri AŞIRI DÜŞÜK
#Grup 3 Emekli-Esnaf Limitler Düşük - Orta
#Grup 1 Beyaz-Altın Yakalılar Limitler Yüksek
#Grup 2 Mavi Yakalılar Çünkü Limitler Orta

,kaProductKodu,kaOncekiLimit,kaEkstreKodu,KartSubeKodu,kaEkstreStatu,kaEMailOnlyFlag,EkstreTalimatEmailEv,EkstreTalimatGSMSMS,kaProfilTaksitSayisi,PortfolioClass,FundingAmount,Status,FundingFER,FundingAmountDebitCorrespond,FundingAmountCorrespond,IsLifeInsurance,Score,Grup,CustomerId
3,CLESVISALE,0,23,114,2,1,1,0,0,2,4219.00,5,0.000,4219.00,4219.00,0,1779,0,140492
4,CLESVISALE,0,23,114,2,1,1,0,0,2,6010.00,5,0.000,6010.00,6010.00,0,1779,0,140492
17,VISALESB,2500,23,77,2,1,1,0,0,2,6014.56,5,0.000,6014.56,6014.56,0,1860,0,1356046
18,VISALESB,2500,23,77,2,1,1,0,0,2,21847.00,5,0.000,21847.00,21847.00,0,1860,0,1356046
21,CLESVISALE,0,23,108,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1760,0,1351964
29,CLESVISALE,0,30,127,2,1,1,0,0,2,4840.00,5,0.000,4840.00,4840.00,0,1316,0,6207390
30,CLESVISALE,3000,23,85,2,1,1,0,4,0,0.00,0,0.000,0.00,0.00,0,1545,0,616931
40,CLESVISALE,0,23,128,2,1,0,0,0,2,60000.00,8,1.000,60000.00,60000.00,0,1710,0,352375
41,CLESVISALE,0,23,128,2,1,0,0,0,2,10549.95,5,0.000,10549.95,10549.95,0,1710,0,352375
42,CLESVISALE,0,23,128,2,1,0,0,0,2,27.50,5,0.000,27.50,27.50,0,1710,0,352375
45,VISALESB,10000,23,112,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1589,0,217241
46,VISALESB,10000,8,135,2,1,0,0,0,2,26950.00,5,0.000,26950.00,26950.00,0,1698,0,223000
47,CLESVISALE,0,23,146,2,1,1,0,9,2,10000.00,5,0.000,10000.00,10000.00,0,698,0,834696
48,CLESVISALE,0,23,146,2,1,1,0,9,2,16000.00,5,0.000,16000.00,16000.00,0,698,0,834696
52,CLESVISALE,2500,23,104,2,1,0,0,0,2,12500.00,10,0.000,12500.00,12500.00,0,1786,0,834402
53,CLESVISALE,2500,23,104,2,1,0,0,0,2,12500.00,8,1.000,12500.00,12500.00,0,1786,0,834402
61,CLESVISALE,2500,8,111,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1477,0,6776986
65,CLESVISALE,0,30,102,2,1,1,0,0,2,9000.00,10,0.000,9000.00,9000.00,0,1264,0,781821
66,CLESVISALE,0,30,102,2,1,1,0,0,2,7500.00,8,1.000,7500.00,7500.00,0,1264,0,781821
67,VISALESB,2000,30,117,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1399,0,6913804
73,SAGLAMPL,19800,23,104,2,1,0,0,0,2,30000.00,7,0.000,30000.00,30000.00,0,1860,0,58155
104,SAGLAMPL,0,23,149,2,1,1,0,0,2,13500.00,5,0.000,13500.00,13500.00,0,1450,0,487148
107,CLESVISALE,0,30,80,2,1,1,0,3,0,0.00,0,0.000,0.00,0.00,0,383,0,560388
116,SAGLAMPL,0,23,100,2,1,1,0,0,2,9000.00,8,1.000,9000.00,9000.00,0,1686,0,598665
119,CLESVISALE,2001,30,75,2,1,1,0,0,2,10000.00,5,0.000,10000.00,10000.00,0,1483,0,625386
121,SAGLAMPL,0,23,148,2,1,1,0,0,2,5000.00,8,1.000,5000.00,5000.00,0,1513,0,641517
122,SAGLAMPL,0,23,148,2,1,1,0,0,2,2976.25,5,0.000,2976.25,2976.25,0,1513,0,641517
125,CLESVISALE,1000,30,132,2,1,1,0,0,2,21000.00,10,1.000,21000.00,21000.00,0,1346,0,677567
126,CLESVISALE,1000,30,132,2,1,1,0,0,2,21000.00,8,1.000,21000.00,21000.00,0,1346,0,677567
127,CLESVISALE,1000,23,126,2,1,1,0,4,2,22000.00,7,1.000,22000.00,22000.00,0,1230,0,691423
129,SAGLAMPL,7000,23,79,2,1,1,0,0,2,6000.00,8,1.000,6000.00,6000.00,0,1568,0,698981
130,SAGLAMPL,7000,23,79,2,1,1,0,0,2,20000.00,10,0.000,20000.00,20000.00,0,1568,0,698981
131,SAGLAMPL,7000,23,79,2,1,1,0,0,2,20000.00,8,1.000,20000.00,20000.00,0,1568,0,698981
132,SAGLAMPL,8000,23,74,2,1,1,0,0,2,10500.00,5,0.000,10500.00,10500.00,0,1656,0,702453
133,SAGLAMPL,0,23,119,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1385,0,702957
134,SAGLAMPL,0,8,78,2,1,1,0,0,2,11000.00,8,1.000,11000.00,11000.00,0,1248,0,712917
136,CLESVISALE,0,30,114,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1900,0,727191
139,CLESVISALE,0,8,82,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1633,0,732361
143,SAGLAMPL,0,30,143,2,1,1,0,0,2,1044.00,5,0.000,1044.00,1044.00,0,1568,0,735016
144,SAGLAMPL,0,30,143,2,1,1,0,0,2,1750.00,11,2.889,5055.75,5055.75,0,1568,0,735016
145,SAGLAMPL,0,23,133,2,1,1,0,0,2,3900.00,5,0.000,3900.00,3900.00,0,1595,0,744900
146,SAGLAMPL,0,23,133,2,1,1,0,0,2,1642.89,5,0.000,1642.89,1642.89,0,1595,0,744900
149,CLESVISALE,700,30,106,2,1,0,0,0,0,0.00,0,0.000,0.00,0.00,0,1633,0,758679
151,SAGLAMPL,4000,30,139,2,1,1,0,10,0,0.00,0,0.000,0.00,0.00,0,1568,0,760495
152,SAGLAMPL,18000,30,155,2,1,1,0,0,2,20000.00,7,0.000,20000.00,20000.00,0,1606,0,779166
165,SAGLAMPL,0,23,146,2,1,1,0,9,2,10000.00,5,0.000,10000.00,10000.00,0,698,0,834696
166,SAGLAMPL,0,23,146,2,1,1,0,9,2,16000.00,5,0.000,16000.00,16000.00,0,698,0,834696
169,SAGLAMPL,0,30,119,2,1,0,0,3,0,0.00,0,0.000,0.00,0.00,0,1809,0,851504
179,SAGLAMPL,0,23,108,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1760,0,1351964
189,SAGLAMPL,0,23,79,2,1,1,0,0,2,2550.00,5,0.000,2550.00,2550.00,0,1169,0,6055542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,SAGLAMMCSB,2000,30,134,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1578,0,10088446
2467,SAGLAMMCSB,0,30,107,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1648,0,10090107
2470,MCSALESB,3000,23,123,2,1,1,0,0,2,800.00,5,0.000,800.00,800.00,0,1860,0,10112747
2473,SAGLAMMCSB,130,23,149,2,1,1,0,5,0,0.00,0,0.000,0.00,0.00,0,1747,0,10128301
2474,SAGLAMMC,0,30,126,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,921,0,10134114
2486,SAGLAMMCSB,0,30,127,2,1,1,0,0,2,3.58,7,1.000,3.58,3.58,0,1698,0,10208333
2493,MCSALESB,0,30,135,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1195,0,10238900
2502,MCSALESB,0,30,137,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1826,0,19062677
2511,MCSALESB,3000,30,74,2,1,1,0,3,0,0.00,0,0.000,0.00,0.00,0,1651,0,19106591
2513,SAGLAMMCSB,0,30,160,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1826,0,19113479
2516,MCSALESB,0,30,77,2,1,1,0,4,0,0.00,0,0.000,0.00,0.00,0,1101,0,19115728
2517,MCSALESB,0,30,112,2,1,1,0,0,2,2018.85,5,0.000,2018.85,2018.85,0,1578,0,19115861
2522,MCSALESB,2500,30,85,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,132,0,19140803
2525,SAGLAMMC,0,30,76,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1291,0,91002172
2532,SAGLAMMCSB,1000,23,81,2,1,1,0,2,0,0.00,0,0.000,0.00,0.00,0,1373,0,91056168
2533,MCSALESB,0,30,129,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1373,0,91056168
2535,ClessSALE,2000,30,76,2,1,1,0,0,2,9000.00,5,0.000,9000.00,9000.00,0,1428,0,91064378
2536,ClessSALE,2000,30,76,2,1,1,0,0,2,1840.00,5,0.000,1840.00,1840.00,0,1428,0,91064378
2538,SAGLAMMCSB,0,23,133,2,1,1,0,10,0,0.00,0,0.000,0.00,0.00,0,1406,0,91083236
2541,SAGLAMMC,7500,30,83,2,1,1,0,5,2,6000.00,5,0.000,6000.00,6000.00,0,1369,0,91087593
2547,MCSALESB,3000,30,116,2,1,1,0,3,2,2610.98,5,0.000,2610.98,2610.98,0,1622,0,91120144
2549,MCSALESB,0,30,154,2,1,1,0,0,2,2099.00,5,0.000,2099.00,2099.00,0,1568,0,91127060
2550,MCSALESB,500,30,84,2,1,1,0,0,2,2400.00,3,0.000,2400.00,2400.00,0,1805,0,91127279
2551,MCSALESB,500,30,84,2,1,1,0,0,2,1908.90,5,0.000,1908.90,1908.90,0,1805,0,91127279
2552,MCSALESB,1000,30,85,2,1,1,0,0,2,3786.00,5,0.000,3786.00,3786.00,0,1668,0,91127843
2553,MCSALESB,1000,30,85,2,1,1,0,0,2,3550.00,5,0.000,3550.00,3550.00,0,1668,0,91127843
2554,MCSALESB,0,30,130,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1698,0,91130957
2558,ClessSALE,0,30,148,2,1,1,0,0,2,650.00,5,0.000,650.00,650.00,0,1633,0,91137281
2566,ClessSALE,0,23,80,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1428,0,91162413
2575,SAGLAMMCSB,3000,23,135,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1537,0,91176389
2576,MCSALESB,0,30,137,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1459,0,91179797
2579,MCSALESB,0,30,103,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1760,0,91206727
2589,MCSALESB,1500,23,122,2,1,1,0,3,2,1675.00,5,0.000,1675.00,1675.00,0,1633,0,91227247
2592,MCSALESB,5000,30,129,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1747,0,91262643
2597,MCSALESB,1000,30,145,2,1,1,0,0,2,2090.71,5,0.000,2090.71,2090.71,0,1433,0,91279918
2599,MCSALESB,1000,23,105,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1706,0,91286804
2604,MCSALESB,0,30,89,2,1,1,0,3,0,0.00,0,0.000,0.00,0.00,0,1747,0,93636985
2612,MCSALESB,2000,30,131,2,1,1,0,0,2,5944.00,5,0.000,5944.00,5944.00,0,1786,0,93683605
2615,SAGLAMMCSB,3000,15,135,2,1,1,0,3,0,0.00,0,0.000,0.00,0.00,0,1860,0,93692855
2618,SAGLAMMC,0,30,127,2,1,1,0,6,0,0.00,0,0.000,0.00,0.00,0,1735,0,93725060
2637,MCSALESB,0,30,103,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1365,0,93987735
2648,SAGLAMMCSB,2000,30,105,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1760,0,94166993
2649,MCSALESB,3000,30,104,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1584,0,94168611
2652,SAGLAMMC,0,30,147,2,1,1,0,2,0,0.00,0,0.000,0.00,0.00,0,1668,0,94218952
2656,SAGLAMMCSB,1000,23,109,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1826,0,94248962
2658,SAGLAMMC,3500,30,114,2,1,1,0,6,0,0.00,0,0.000,0.00,0.00,0,1792,0,94258805
2662,SAGLAMMCSB,0,30,158,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1826,0,94279401
2663,MCSALESB,0,30,158,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1826,0,94279401
2665,MCSALESB,1000,30,119,2,1,1,0,0,0,0.00,0,0.000,0.00,0.00,0,1809,0,94289005
2670,SAGLAMMCSB,2000,30,104,2,1,1,0,3,0,0.00,0,0.000,0.00,0.00,0,1760,0,94590805